import type { Metadata } from "next";
import { Roboto, Judson } from "next/font/google";
import "./globals.scss";

const judson = Judson({
  subsets: ["latin"],
  weight: ["400"],
});

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${judson.className} ${roboto.className}`}>
        {children}
      </body>
    </html>
  );
}
